name: Android CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      GITHUB_ACTOR: ${{ secrets.CI_BOT_USERNAME }}
      GITHUB_TOKEN: ${{ secrets.CI_BOT_PAT }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 11

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('dependencies.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Retrieve tag
        run: echo "TAG=$(git tag --points-at HEAD)" >> $GITHUB_ENV

      - name: Build and test
        run: ./gradlew test assembleRelease

      - name: Create github release
        if: env.TAG != ''
        id: create-release
        uses: softprops/action-gh-release@v1
        with:
          name: Version ${{env.TAG}}
          body: See [CHANGELOG](https://github.com/${{github.repository}}/blob/${{env.TAG}}/CHANGELOG.md) for release notes.
          prerelease: ${{ env.TAG == '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish release
        if: env.TAG != ''
        run: ./gradlew barcode-scanner:publishReleasePublicationToGithubRepository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}